=== simobe-git/tesina-vediamo-che-succede/lweb-tesina/xsd/richieste_crediti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="richiesteCrediti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="richiesta" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="username" type="xsd:string"/>
                            <xsd:element name="crediti" type="xsd:integer"/>
                            <xsd:element name="data" type="xsd:date"/>
                            <xsd:element name="status" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== simobe-git/tesina-vediamo-che-succede/lweb-tesina/xml/richieste_crediti.xml
<?xml version="1.0" encoding="UTF-8"?>
<richiesteCrediti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/richieste_crediti.xsd">
    <richiesta>
        <username>cliente1</username>
        <crediti>100</crediti>
        <data>2024-10-16</data>
        <status>in attesa</status>
    </richiesta>
    <richiesta>
        <username>cliente2</username>
        <crediti>50</crediti>
        <data>2024-10-15</data>
        <status>approvata</status>
    </richiesta>
    <richiesta>
        <username>cliente3</username>
        <crediti>200</crediti>
        <data>2024-10-14</data>
        <status>rifiutata</status>
    </richiesta>
    <richiesta>
        <username>cliente1</username>
        <crediti>34</crediti>
        <data>2025-01-21</data>
        <status>in attesa</status>
    </richiesta>
    <richiesta>
        <username>admin1</username>
        <crediti>34</crediti>
        <data>2025-01-21</data>
        <status>rifiutata</status>
    </richiesta>
</richiesteCrediti>
