=== simobe-git/tesina-vediamo-che-succede/lweb-tesina/dtd/utenti.dtd
<!ELEMENT utenti (utente+)>
<!ELEMENT utente (username, ruolo, avatar)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT ruolo (#PCDATA)>
<!ELEMENT avatar (#PCDATA)>

=== simobe-git/tesina-vediamo-che-succede/lweb-tesina/xml/utenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE utenti SYSTEM "../dtd/utenti.dtd">

<utenti>
  <utente>
    <username>cliente1</username>
    <ruolo>richiesta_admin</ruolo>
    <avatar>avatar1.jpg</avatar>
  </utente>
  <utente>
    <username>admin1</username>
    <ruolo>admin</ruolo>
    <avatar>default_avatar.jpg</avatar>
  </utente>
  <utente>
    <username>bella</username>
    <ruolo>cliente</ruolo>
    <avatar>default_avatar.jpg</avatar>
  </utente>
  <utente>
    <username>belli</username>
    <ruolo>cliente</ruolo>
    <avatar>default_avatar.jpg</avatar>
  </utente>
  <utente>
    <username>simonesimonesimone</username>
    <ruolo>cliente</ruolo>
    <avatar>default_avatar.jpg</avatar>
  </utente>
  <utente>
    <username>cliente3</username>
    <ruolo>cliente</ruolo>
    <avatar>avatar2.jpg</avatar>
  </utente>
</utenti>
